services:
  - type: web
    name: diabetes-dl-api
    env: docker
    dockerfilePath: ./Dockerfile
    docker:
      context: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    healthCheckPath: /
    autoDeploy: true
    maxShutdownDelay: 30

